config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'

  get 'teas/featured' => 'teas#featured'

  resources :teas

end

app/models/tea.rb
class Tea < ActiveRecord::Base
  validates :name, presence: true
  scope :expensive, -> { where("price >= ?", 50) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/teas_controller.rb
class TeasController < ApplicationController

  def index
    @teas = Tea.all
    render json: @teas
  end

  def featured
    @teas = Tea.expensive
    render json: @teas
  end

  def show
    @tea = Tea.find(params[:id])
    render json: @tea
  end

  def new
    @tea = Tea.new
  end

  def edit

  end

  def create
    @tea = Tea.new(tea_params)

    if @tea.save
      redirect_to @tea
    else
      render 'new'
    end
  end

  def update

  end

  private
    def tea_params
      params.require(:tea).permit(:name, :price, :description)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teas_helper.rb
module TeasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Tea Shop API</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="teaShop" ng-controller="MainCtrl">

  <section class="jumbotron text-xs-center">
        <div class="container">
          <h1 class="jumbotron-heading">Tea Shop API</h1>
          <p class="lead text-muted">Tea Catalog</p>
          <p>
            <a href="/teas/" class="btn btn-primary">Full catalog</a>
            <a href="/teas/new" class="btn btn-secondary">Add a new tea</a>
          </p>
        </div>
      </section>

<%= yield %>

</body>
</html>

app/views/teas/index.html.erb
<div class="container">
  <div class="row">
    <h1>Listing Teas</h1>
    <%= link_to 'New tea', new_tea_path %>
  </div>

  <div class="row">
    <div class="card-columns">
      <% @teas.each do |tea| %>
      <div class="col-sm-4">
        <div class="card">
          <div class="card-header">
            Price:
            <%= tea.price %>
            <i class="fa fa-usd"></i>
          </div>
          <% if tea.image? %>
          <img alt='<%= tea.name %>' class="img-fluid" src='<%= tea.image %>'>
          <% end %>
          <div class="card-block">
            <h4 class="card-title"><%= tea.name %></h4>
            <p class="card-text"><%= tea.description %></p>
          </div>
          <div class="card-block">
            <a class="card-link" href='<%= tea.link %>'>Details</a>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>

</div>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Description</th>
  </tr>

  <% @teas.each do |tea| %>
  <tr>
    <td><%= tea.name %></td>
    <td><%= tea.price %></td>
    <td><%= tea.description %></td>
  </tr>
  <% end %>
</table>

app/views/teas/new.html.erb
<div class="container">
  <h2>Add New Tea</h2>

  <%= form_for :tea, url: teas_path do |f| %>

      <% if @tea.errors.any? %>
          <div id="error_explanation">
            <h2>
              <%= pluralize(@tea.errors.count, "error") %> prohibited
              this tea from being saved:
            </h2>
            <ul>
              <% @tea.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <fieldset class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :price %>
        <%= f.text_area :price, class: 'form-control' %>
      </fieldset>

      <fieldset class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
      </fieldset>

      <div class="btn-group" role="group" aria-label="form actions">
        <%= f.submit class: 'btn btn-primary' %>

        <%= link_to 'Back', teas_path, class: 'btn btn-secondary' %>
      </div>
  <% end %>


</div>

app/views/teas/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @tea.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @tea.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tea.description %>
</p>

<%= link_to 'Back', teas_path %>

app/views/welcome/index.html.erb
<div class="container">
  <h2>API Calls</h2>
  <ul>
    <li>
      <%= link_to 'Teas Catalog', controller: 'teas' %>
    </li>

    <li>
      Call featured
    </li>

    <li>
      TODO: filter
    </li>

    <li>
      <%= link_to 'Teas Catalog Add new', controller: 'teas', action: 'new' %>
    </li>

    <li>
      Angular test: {{test}}
    </li>
  </ul>

</div>